### ISSUE TITLE
Username parameter deletes last part of the string per default

### ISSUE THREAD

**Issue by Sebisnow** [nico-amsterdam/pop3mail#1]
It should be mentioned somewhere that the pop3mail download function same as erlpop by nico-amsterdam removes everything after, including th "@" sign per default. While this might work for GMail it is still unintuitive and difficult to figure out, thus it should be mentioned within you documentation.

Still thank you for providing this implementation.

**Comment by nico-amsterdam** [comment]
Í never noticed this.
Indeed erlpop splits the username from the address. I can only guess why this is done.
iex(1)> {uid, adr} = :epop_client.user_address('user@gmail.com')
{'user', 'gmail.com'}

Gmail allows me to login with or without the @gmail.com 
Best solution would be to fix erlpop.

**Comment by nico-amsterdam** [comment]
wget http://www1.erlang.org/contrib/epop-2.9.tgz
tar -xf epop-2.9.tgz
nroff -man epop-2.9/man/man3/epop_client.3

Aha, in 1999 the only way to specify the server was with the UserAddr parameter, and now in 2017 it still requires the @ sign so it can split it into accountname and server address.

**Comment by nico-amsterdam** [comment]
After examing the epop option parser it turns out I don't have to change erlpop at all, because one of the options is the user, so you can connect like this: 

iex(1)> {:ok, client} = :epop_client.connect('user@gmail.com', 'password', [{**:user**, '**user@gmail.com**'}, {:addr, 'pop.gmail.com'}, {:port,995}, :ssl])

This will connect as user: user@gmail.com

The solution is to change my calls to epop_client.connect with this :user option.

**Comment by nico-amsterdam** [comment]
Fixed in v1.1.0
